// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency_injection

import (
	"github.com/Hirochon/value-api/internal/infrastructure/register_user"
	register_user2 "github.com/Hirochon/value-api/internal/usecase/register_user"
	"github.com/Hirochon/value-api/internal/user_interface/rest_api/route"
	"github.com/go-logr/logr"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitRegisterUserInterface(sqlDB *sqlx.DB, registerUserLogger logr.Logger) route.RegisterUserInterface {
	registerUserRepository := register_user.NewRegisterUserRepository(sqlDB, registerUserLogger)
	registerUserUsecase := register_user2.NewRegisterUserUsecase(registerUserRepository, registerUserLogger)
	registerUserInterface := route.NewRegisterUserInterface(registerUserUsecase, registerUserLogger)
	return registerUserInterface
}
